### ISSUE TITLE
Link to Paper Draft: https://drive.google.com/open?id=0B-FMQiI1smI0c1hUdUR0S19BLVU

### ISSUE THREAD

**Issue by tinoreskovic** [tinoreskovic/Mass-Media-Independent-Research#21]
Please find the draft at the link in the title; alternatively, the pdf's location is: Google Drive -> Mass Media -> Tin -> Tin Oreskovic - Draft.pdf

**Comment by jmshapir** [comment]
@tinoreskovic task received, hope to post comments soon

**Comment by jmshapir** [comment]
@tinoreskovic my comments here: [tin_jms.pdf](https://github.com/tinoreskovic/Mass-Media-Independent-Research/files/964287/tin_jms.pdf)

You should be sure to collect comments fro the others who do not have other specific tasks this week.

Let's try to incorporate these by Monday so that we can finalize a plan to submit.
