### ISSUE TITLE
Andrew

### ISSUE THREAD

**Issue by awjiang** [tinoreskovic/Mass-Media-Independent-Research#22]
Draft is in Google Drive under my name. Model, Results, and Discussion are new

**Comment by jmshapir** [comment]
@awjiang task received, hope to send comments soon

**Comment by jmshapir** [comment]
[andrew_jms.pdf](https://github.com/tinoreskovic/Mass-Media-Independent-Research/files/965823/andrew_jms.pdf)

Here you go @awjiang. Let's have everyone who doesn't have something else on their plate take a pass too. You should be able to knock these off pretty quickly so that we can finalize a plan for submission when we talk on Monday.

**Comment by msanwalk** [comment]
Please find edits / comments attached: [Draft[Conflict].pdf](https://github.com/tinoreskovic/Mass-Media-Independent-Research/files/984525/Draft.Conflict.pdf)
