### ISSUE TITLE
Mili's paper - comments

### ISSUE THREAD

**Issue by msanwalk** [tinoreskovic/Mass-Media-Independent-Research#23]
Here's the link: https://drive.google.com/open?id=1fypk5zmS5r8fL3ZW0ZnQf_8xe9HFv6qPctj7kvihaNA

**Comment by jmshapir** [comment]
@msanwalk task received, hope to send comments soon

**Comment by jmshapir** [comment]
[mili_jms.pdf](https://github.com/tinoreskovic/Mass-Media-Independent-Research/files/964636/mili_jms.pdf)

@msanwalk here you go!

**Comment by gbreynol** [comment]
Hey Mili, a few comments:

- I found the second sentence of the second paragraph of the intro section very confusing. I read it a couple of times and still couldn't really figure out what you were trying to say. There are multiple other times when you write run-ons, which you may want to clean up, but this was the worst one I thought

- I thought Figure 1 was a bit confusing. I think that you were graphing number of deaths on the x axis and persons affect on the y, but i wasn't sure. I think it would be helpful to add a y axis label here, and there were a couple of other graphs where I thought a y axis label would be nice as well.

- One of your main assumptions is that media coverage dramatically drops off after 10 days. This seemed a bit arbitrary to me (i.e. why not one week, or two weeks), and I think a quick explanation/justification would be nice.

- This one is more of a personal preference thing. You use the word "since" a ton as a synonym for "because". You can do that, but "because" is a secondary, not primary, definition of "since," so I would do this sparingly if I were you and replace most "since"s with "because"s. But again, that's more of a personal preference thing
